name = "Celebrant"
license = "MIT"
licenselink = "https://github.com/Zac-Benattar/celebrant/blob/main/LICENSE"
description = "Hugoplate is a free starter template built with Hugo, and TailwindCSS, providing everything you need to jumpstart your Hugo project and save valuable time."
homepage = "https://github.com/Zac-Benattar/celebrant"
demosite = "https://zeon.studio/preview?project=hugoplate"
min_version = "0.141.0"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Decap CMS",
  "TailwindCSS",
  "Search",
  "Multilingual",
  "Dark Mode",
]

[author]
name = "Zac Benattar"
homepage = "https://zcbn.dev"

[original]
author = "Zeon Studio"
homepage = "https://zeon.studio"
repo = "https://github.com/zeon-studio/themeplate"
