backend:
  name: git-gateway
  branch: main
  display_url: '<site_url>/'
  logo_url: '<site_url>/images/logo.png'
  commit_messages:
    create: '{{author-name}} Create {{collection}} “{{slug}}”'
    update: '{{author-name}}Update {{collection}} “{{slug}}”'
    delete: '{{author-name}}Delete {{collection}} “{{slug}}”'
    uploadMedia: '{{author-name}}Upload “{{path}}”'
    deleteMedia: '{{author-name}}Delete “{{path}}”'
    openAuthoring: '{{author-name}} - {{message}}'
media_folder: "assets/images" # Folder where user uploaded files should go
public_folder: "images"
# For local testing
local_backend: true
# npx netlify-cms-proxy-server (in another terminal)
collections:
  - label: "Blog Post" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/post
    folder: "content/english/blog" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "list", add_to_top: true, default: ["news"]}
      - { label: "Tags", name: "tags", widget: "list", add_to_top: true, default: ["wedding"]}
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages" 
    name: "pages"
    create: false
    files:
      - label: "Home Page"
        name: "home"
        file: "content/english/_index.md"
        preview_path: "/"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Home" }
          - {
              label: "Banner",
              name: "banner",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Tagline 1", name: "tagline1", hint: "First line of your homepage, small, bold, cursive font", widget: "string" },
                  { label: "Tagline 2", name: "tagline2", hint: "Second line of your homepage, big, bold, multi-line, cursive font", widget: "string" },
                  { label: "Tagline 3", name: "tagline3", hint: "Third line of your homepage, small, multi-line, normal font", widget: "string" }, 
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Button", name: "button", widget: "object", fields: 
                    [
                      { label: "Enable", name: "enable", widget: "boolean", defualt: true }, 
                      { label: "Label", name: "label", widget: "string" }, 
                      { label: "Link", name: "link", widget: "string", default: "/contact" }
                    ]
                  }
                ],
            }
          - {
              label: "Features",
              name: "features",
              widget: "list",
              summary: "{{fields.title}}",
              fields:
              [
                { label: "Title", name: "title", hint: "Title of the section, big, bold, cursive font", widget: "string" },
                { label: "Image", name: "image", widget: "image" },
                { label: "Tagline", name: "tagline", hint: "A sort of subheading under the title of the section", widget: "text" },
                { label: "Bullet Points, comma separated list (dont use with text)", name: "bulletpoints", hint: "Don't use with the text option", widget: "list" },
                { label: "Text (dont use with bullet points)", name: "text", hint: "Don't use with the bullet point option", widget: "string" },
                { label: "Button", name: "button", widget: "object", fields: 
                    [
                      { label: "Enable", name: "enable", widget: "boolean", defualt: true }, 
                      { label: "Label", name: "label", widget: "string" }, 
                      { label: "Link", name: "link", widget: "string", default: "/contact" }
                    ]
                  }
              ]
            }
          - {
              label: "End Call to Action",
              name: "end_cta",
              widget: "object",
              fields:
                [
                  { label: "Tagline", name: "tagline", hint: "Displayed at the bottom of the homepage with a link to contact.", widget: "string" },
                  { label: "Button", name: "button", widget: "object", fields: 
                    [
                      { label: "Enable", name: "enable", widget: "boolean", defualt: true }, 
                      { label: "Label", name: "label", widget: "string" }, 
                      { label: "Link", name: "link", widget: "string", default: "/contact" }
                    ]
                  }
                ],
            }
      - label: "About"
        name: "about"
        file: "content/english/about/_index.md"
        preview_path: "/about"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", hint: "Write about yourself. /n for a line break, /n/n for a paragraph break", widget: "text" }
      - label: "Contact"
        name: "contact"
        file: "content/english/contact/_index.md"
        preview_path: "/contact"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Banner", name: "banner", widget: "object", fields: 
              [
                { label: "Tagline 1", name: "tagline1", widget: "string" },
                { label: "Tagline 2", name: "tagline2", widget: "string" },
              ]
            }
          - { label: "Message Box", name: "message_textarea", widget: "object", fields: 
              [
                { label: "Title", name: "title", widget: "string" },
                { label: "Description", name: "description", widget: "string" },
              ]
            }
          - { label: "Body", name: "body", hint: "Not required", widget: "text" }
      - label: "Privacy Policy"
        name: "privacy"
        file: "content/english/pages/privacy-policy.md"
        preview_path: "/privacy-policy"
        delete: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body (markdown)", name: "body", hint: "Written in markdown. Use hashtags for headers. Make sure this is accurate as it is a legal document.", widget: "text" }